export const artists = [
  "_NSYNC",
  "Ace of Base",
  "Adele",
  "Alan Walker",
  "Alessia Cara",
  "Alle Farben",
  "Andy Grammer",
  "Arash",
  "Arctic Monkeys",
  "Ariana Grande",
  "AURORA",
  "Ava Max",
  "Avicii",
  "B.o.B",
  "Becky G",
  "Bill Withers",
  "Billie Eilish",
  "blackbear",
  "Blue",
  "Boney M_",
  "Calvin Harris",
  "Chamillionaire",
  "Charli xcx",
  "Chris Brown",
  "Cigarettes After Sex",
  "Clean Bandit",
  "Compilations",
  "Coolio",
  "Coyote Theory",
  "Culcha Candela",
  "Daft Punk",
  "David Guetta",
  "Demi Lovato",
  "Dua Lipa",
  "Ed Sheeran",
  "Ellie Goulding",
  "Elton John _ Leon Russell",
  "Elton John",
  "Em Beihold",
  "Eminem",
  "Fall Out Boy",
  "Fergie",
  "Flume",
  "French Montana",
  "G-Eazy",
  "George Michael",
  "Ghost",
  "Gotye",
  "Green Day",
  "Gym Class Heroes",
  "Iggy Azalea",
  "Imagine Dragons",
  "ItaloBrothers",
  "James Arthur",
  "Jamie xx",
  "Jax Jones",
  "John Newman",
  "Josh Turner",
  "Justin Bieber",
  "Justin Timberlake",
  "Keane",
  "Khalid",
  "Kim Deal",
  "Lady Gaga",
  "Lana Del Rey",
  "Lena",
  "Liam Payne",
  "Lil Nas X",
  "Loreen",
  "Lukas Graham",
  "Macklemore & Ryan Lewis",
  "Martin Garrix",
  "MEDUZA",
  "Michael Buble",
  "Mr. President",
  "Mustard",
  "NF",
  "Nickelback",
  "Olivia Rodrigo",
  "OneRepublic",
  "OutKast",
  "Peter Fox",
  "Phillip Phillips",
  "Post Malone",
  "Queen",
  "R3HAB",
  "Rihanna",
  "Robin Schulz",
  "Roddy Ricch",
  "ROSÉ",
  "Sade",
  "San Holo",
  "Seafret",
  "Sean Kingston",
  "Seeed",
  "SHAED",
  "Shakira",
  "Shawn Mendes",
  "Sia",
  "Sido",
  "Soap&Skin",
  "Sofia Reyes",
  "Stephen Dawes",
  "Stephen Sanchez",
  "Suki Waterhouse",
  "t.A.T.u_",
  "T.I_",
  "Tame Impala",
  "Tate McRae",
  "Taylor Swift",
  "The Animals",
  "The BossHoss",
  "The Chainsmokers",
  "Tiesto",
  "Timmy Trumpet",
  "Tones and I",
  "Travis Scott",
  "Trevor Daniel",
  "Tyga",
  "Vance Joy",
  "VIZE x ALOTT",
  "WILLOW",
  "Wiz Khalifa",
  "YUNGBLUD",
];

// const cleaned = artists.map((artist) => {
//   return artist.trim().replace(/'/g, "");
// });

// console.log(JSON.stringify(cleaned, null, 2));
